#define CHEAT_FLAGHACK   1
#define CHEAT_EDITHACK   2
#define CHEAT_EDITMSG    3
#define CHEAT_WRONGGUN   4
#define CHEAT_INSTAGUN   5
#define CHEAT_EXPLOSION  6
#define CHEAT_NOAMMO     7
#define CHEAT_FASTRELOAD 8
#define CHEAT_NOTALIVE   9
#define CHEAT_NORAYS     10
#define CHEAT_GUNRANGE   11
#define CHEAT_GUNRAYS    12
#define CHEAT_PICKUP     13
#define CHEAT_MSGSIZE    14

struct Cheater
{
    uint IP;
};
vector <Cheater> Cheaters;

void AddPban (uint ip)
{
    loopv (Cheaters)
    {
        if (Cheaters [i].IP == ip) return;
    }
    Cheater & Pban = Cheaters.add ();
    Pban.IP = ip;
}

ICOMMAND (pban, "i", (uint * IP), AddPban (* IP));

void Bancheater (clientinfo * ci, const char * Cheat, int CHEAT)
{
    const char * Name = ci->name;
    int Cn = ci->clientnum;
    Cheater & Cur = Cheaters.add ();
    Cur.IP = getclientip (ci->clientnum);
    sendservmsgf ("\f3%s \f4Client \f0%s \f4(\f0%s\f4) has been disconnected for cheating \f4(\f3%s\f4, %i). \f3%s",
        MessageDecoration1,
        Name,
        getclienthostname (Cn),
        Cheat,
        CHEAT,
        MessageDecoration2
    );
    logoutf ("%s Client %s (%s) has been disconnected for cheating (%s). %s",
        MessageDecoration1,
        Name,
        getclienthostname (Cn),
        Cheat,
        MessageDecoration2
    );
    stream *f = openutf8file(cheatfile, "w");
    if(f)
    {
        f->printf("// Automatically generated by HaythServ-v2.0 - do not edit.\n");
        f->printf("// Contains a list of permamently banned cheaters.\n");
        f->printf("// Also contains a list of other permamently banned clients using #pban <cn>.\n\n");
        loopv (Cheaters)
        {
            defformatstring (Message)("pban %u\n", 
                Cheaters [i].IP
            );
            f->printf (Message);
        }
        delete f;
    }
    disconnect_client (ci->clientnum, DISC_IPBAN);
}

int cheater (clientinfo * ci, int Cheat)
{
    if (ci->state.aitype != AI_NONE)
    {
        return -1;
    }
    
    switch (Cheat)
    {
        case CHEAT_FLAGHACK:
            Bancheater (ci, "flag hack", CHEAT_FLAGHACK);
            break;
        case CHEAT_EDITHACK:
            Bancheater (ci, "edit mode in non coop-edit gamemode", CHEAT_EDITHACK);
            break;
        case CHEAT_EDITMSG:
            Bancheater (ci, "edit messages in non coop-edit gamemode", CHEAT_EDITMSG);
            break;
        case CHEAT_WRONGGUN:
            Bancheater (ci, "wrong gun", CHEAT_WRONGGUN);
            break;
        case CHEAT_INSTAGUN:
            Bancheater (ci, "non instagib weapon", CHEAT_INSTAGUN);
            break;
        case CHEAT_EXPLOSION:
            Bancheater (ci, "explosion hack", CHEAT_EXPLOSION);
            break;
        case CHEAT_NOAMMO:
            Bancheater (ci, "no ammo", CHEAT_NOAMMO);
            break;
        case CHEAT_FASTRELOAD:
            Bancheater (ci, "modified weapon reload time", CHEAT_FASTRELOAD);
            break;
        case CHEAT_NOTALIVE:
            Bancheater (ci, "trying to shoot without being alive", CHEAT_NOTALIVE);
            break;
        case CHEAT_NORAYS:
            Bancheater (ci, "disabled gun rays", CHEAT_NORAYS);
            break;
        case CHEAT_GUNRANGE:
            Bancheater (ci, "modified gun range", CHEAT_GUNRANGE);
            break;
        case CHEAT_GUNRAYS:
            Bancheater (ci, "modified gun rays", CHEAT_GUNRAYS);
            break;
        case CHEAT_PICKUP:
            Bancheater (ci, "trying to pickup an item in a m_noitems gamemode", CHEAT_PICKUP);
            break;
        case CHEAT_MSGSIZE:
            Bancheater (ci, "wrong message size", CHEAT_MSGSIZE);
            break;
        default:
            return 0;
    }
    return Cheat;
}
